language: php
php:
    - '7.0'
    - nightly

services:
    - postgresql

addons:
    postgresql: "9.5"

before_install:
    - phpenv config-rm xdebug.ini
    - pecl install domxml
    - pecl install intl

script:
    - ./bin/test