language: php
php:
    - '7.0'
    - nightly

services:
    - postgresql

addons:
    postgresql: "9.4"

before_install:
    - phpenv config-rm xdebug.ini
    - php -i
    - ls /home/travis/.phpenv/versions/7.0/etc/
    - ls /home/travis/.phpenv/versions/7.0/etc/conf.d/
    - pecl install apcu-5.1.3

script:
    - ./bin/test