language: php
php:
    - '7.0'
    - nightly

services:
    - postgresql

addons:
    postgresql: "9.2"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo ''
    - echo "no" | pecl install apcu-5.1.3

script:
    - ./bin/test