language: php
php:
    - '7.0'
    - '7.1'
    - nightly

matrix:
  allow_failures:
    - php: 7.1
    - php: nightly

services:
    - postgresql

addons:
    postgresql: "9.2"

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || true

script:
    - ./bin/test